[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  publish = "dist"
  command = "cp -r src/* dist/"

[dev]
  command = "serve src -l 8080"
  port = 8080
  targetPort = 8080
  publish = "src"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
